export const ENEMY_INFO = [
  {
    id: 'enemy',
    name: 'Gunman',
    world: 'World 1 — Mission Moon',
    specialEffect: 'None — standard damage only.',
    description: 'Gunman — World 1 (Lunar Front).',
  },
  {
    id: 'eagle',
    name: 'Eagle',
    world: 'World 1 — Mission Moon',
    specialEffect: 'None — standard damage only. Aerial, drops bomb projectiles in an arc.',
    description: 'Eagle — World 1 (Lunar Front).',
  },
  {
    id: 'martian_cat',
    name: 'Martian Cat',
    world: 'World 2 — Mars Invasion',
    specialEffect: 'None — standard damage only. ',
    description: 'Martian Cat — World 2 (Mars Invasion).',
  },
  {
    id: 'frog',
    name: 'Frog',
    world: 'World 2 — Mars Invasion',
    specialEffect: 'None — standard contact damage only. No ranged attack, hops toward/around the player.',
    description: 'Frog — World 2 (Mars Invasion).',
  },
  {
    id: 'yeti',
    name: 'Yeti',
    world: 'World 3 — Neon Tundra',
    specialEffect: 'Damage + Freeze — hit locks player movement/jump/shoot for 1-1.5s.',
    description: 'Yeti — World 3 (Neon Tundra).',
  },
  {
    id: 'icy_bee',
    name: 'Icy Bee',
    world: 'World 3 — Neon Tundra',
    specialEffect: 'Damage + Freeze — hit locks player movement/jump/shoot for 1-1.5s. Spawned by the Spaceship, dies in 2 hits.',
    description: 'Icy Bee — World 3 (Neon Tundra).',
  },
  {
    id: 'spaceship',
    name: 'Hive Spaceship',
    world: 'World 3 — Neon Tundra',
    specialEffect: 'None — standard damage only. Spawns up to 3 Icy Bees, then transforms into an attacking Queen Bee form once all bees are dead.',
    description: 'Hive Spaceship — World 3 (Neon Tundra).',
  },
  {
    id: 'vortex',
    name: 'Vortex',
    world: 'World 4 — Farthest Black Hole',
    specialEffect: 'Damage + Teleport — contact mirrors the player\'s position across the arena instead of just damaging.',
    description: 'Vortex — World 4 (Farthest Black Hole).',
  },
  {
    id: 'dark_matter_being',
    name: 'Dark Matter Being',
    world: 'World 4 — Farthest Black Hole',
    specialEffect: 'Standard damage + pulls the player toward it if they stand still for 0.5s+.',
    description: 'Dark Matter Being — World 4 (Farthest Black Hole).',
  },
  {
    id: 'shapeshifter',
    name: 'Shapeshifter',
    world: 'World 5 — Multiverse Endgame',
    specialEffect: 'None — standard damage only. Disguises itself as a copy of the player between attack phases and reflects damage.',
    description: 'Shapeshifter — World 5 (Void Rift).',
  },
  {
    id: 'reg',
    name: 'REG',
    world: 'World 5 — Multiverse Endgame',
    specialEffect: 'Varies — cycles randomly between 5 other enemy forms (and their effects) every few seconds.',
    description: 'REG — World 5 (Void Rift).',
  },
  {
    id: 'time_gunman',
    name: 'Time Gunman',
    world: 'World 5 — Multiverse Endgame',
    specialEffect: 'None — standard damage only. Spawned by the TimeDistorter boss. ',
    description: 'Time Gunman — World 5 (Void Rift).',
  },
];
