export const SHOP_CATALOG = [
  {
    id: 'skin_01',
    category: 'skin',
    name: 'Skin 01',
    price: 200,
    description: 'Placeholder character skin 01',
    spritePath: '/sprites/player.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_02',
    category: 'skin',
    name: 'Skin 02',
    price: 300,
    description: 'Placeholder character skin 02',
    spritePath: '/sprites/player2.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_03',
    category: 'skin',
    name: 'Skin 03',
    price: 400,
    description: 'Placeholder character skin 03',
    spritePath: '/sprites/player3.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_04',
    category: 'skin',
    name: 'Skin 04',
    price: 500,
    description: 'Placeholder character skin 04',
    spritePath: '/sprites/time_gunman.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_05',
    category: 'skin',
    name: 'Skin 05',
    price: 600,
    description: 'Placeholder character skin 05',
    spritePath: '/sprites/shapeshifter.png',
    spriteColumns: 4,
    spriteRows: 3,
  },
  ...Array.from({ length: 5 }, (_, index) => ({
    id: `bullet_${String(index + 1).padStart(2, '0')}`,
    category: 'bulletSkin',
    name: `Bullet Skin ${String(index + 1).padStart(2, '0')}`,
    price: 150 + index * 50,
    description: `Placeholder bullet skin ${String(index + 1).padStart(2, '0')}`,
    spritePath: `/sprites/bullet_placeholder_${String(index + 1).padStart(2, '0')}.png`,
  })),
];