export const SHOP_CATALOG = [
  {
    id: 'skin_01',
    category: 'skin',
    name: 'Starfall Trooper',
    price: 200,
    description: 'Placeholder character skin 01',
    spritePath: '/sprites/player.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_02',
    category: 'skin',
    name: 'Iron Horse Outlaw',
    price: 300,
    description: 'Placeholder character skin 02',
    spritePath: '/sprites/player2.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_03',
    category: 'skin',
    name: 'Titan Plate',
    price: 400,
    description: 'Placeholder character skin 03',
    spritePath: '/sprites/player3.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_04',
    category: 'skin',
    name: 'Carn-evil',
    price: 500,
    description: 'Placeholder character skin 04',
    spritePath: '/sprites/player4.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'skin_05',
    category: 'skin',
    name: 'Blood Baddie',
    price: 600,
    description: 'Placeholder character skin 05',
    spritePath: '/sprites/player5.png',
    spriteColumns: 4,
    spriteRows: 4,
  },
  {
    id: 'bullet_01',
    category: 'bulletSkin',
    name: 'Bullet Skin 01',
    price: 150,
    description: 'Placeholder bullet skin 01',
    spritePath: '/sprites/bullet_placeholder_01.png',
  },
  {
    id: 'bullet_02',
    category: 'bulletSkin',
    name: 'Green Arrow',
    price: 200,
    description: 'A sharp green arrow bolt.',
    previewType: 'canvas',
  },
  {
    id: 'bullet_03',
    category: 'bulletSkin',
    name: 'Blood Drop',
    price: 250,
    description: 'A grim crimson droplet, flying sideways.',
    previewType: 'canvas',
  },
  {
    id: 'bullet_04',
    category: 'bulletSkin',
    name: 'Zigzag Volt',
    price: 300,
    description: 'A crackling bolt of jagged energy.',
    previewType: 'canvas',
  },
  {
    id: 'bullet_05',
    category: 'bulletSkin',
    name: 'Balloon Bomb',
    price: 200,
    description: 'A cheerful little balloon on a string.',
    previewType: 'canvas',
  },
];