export const SHOP_CATALOG = [
  {
    id: 'skin_01',
    category: 'skin',
    name: 'Skin 01',
    price: 200,
    description: 'Placeholder character skin 01',
    spritePath: '/sprites/skin_placeholder_01.png',
  },
  {
    id: 'skin_02',
    category: 'skin',
    name: 'Skin 02',
    price: 300,
    description: 'Placeholder character skin 02',
    spritePath: '/sprites/skin_placeholder_02.png',
  },
  {
    id: 'skin_03',
    category: 'skin',
    name: 'Skin 03',
    price: 400,
    description: 'Placeholder character skin 03',
    spritePath: '/sprites/skin_placeholder_03.png',
  },
  {
    id: 'skin_04',
    category: 'skin',
    name: 'Skin 04',
    price: 500,
    description: 'Placeholder character skin 04',
    spritePath: '/sprites/skin_placeholder_04.png',
  },
  {
    id: 'skin_05',
    category: 'skin',
    name: 'Skin 05',
    price: 600,
    description: 'Placeholder character skin 05',
    spritePath: '/sprites/skin_placeholder_05.png',
  },
  {
    id: 'bullet_01',
    category: 'bulletSkin',
    name: 'Bullet Skin 01',
    price: 150,
    description: 'Placeholder bullet skin 01',
    spritePath: '/sprites/bullet_placeholder_01.png',
  },
  {
    id: 'bullet_02',
    category: 'bulletSkin',
    name: 'Bullet Skin 02',
    price: 200,
    description: 'Placeholder bullet skin 02',
    spritePath: '/sprites/bullet_placeholder_02.png',
  },
  {
    id: 'bullet_03',
    category: 'bulletSkin',
    name: 'Bullet Skin 03',
    price: 250,
    description: 'Placeholder bullet skin 03',
    spritePath: '/sprites/bullet_placeholder_03.png',
  },
  {
    id: 'bullet_04',
    category: 'bulletSkin',
    name: 'Bullet Skin 04',
    price: 300,
    description: 'Placeholder bullet skin 04',
    spritePath: '/sprites/bullet_placeholder_04.png',
  },
  {
    id: 'bullet_05',
    category: 'bulletSkin',
    name: 'Bullet Skin 05',
    price: 350,
    description: 'Placeholder bullet skin 05',
    spritePath: '/sprites/bullet_placeholder_05.png',
  },
];